### ISSUE TITLE
[buggy Report] double-spending Revert

### ISSUE THREAD

**Issue by hereokay** [stackup-wallet/stackup-bundler#139]
If I submit a double-payment UserOp to the bundler that I send to myself, the bundler loses the gas fee.

example)
i have AA wallet. and 0.9 MATIC but If you send me a UserOp that sends me 0.5 MATICs twice at the same time, here's what happens.
<img width="1204" alt="스크린샷 2023-04-06 오후 5 39 53" src="https://user-images.githubusercontent.com/79696571/230594824-7008e39c-a642-4870-8579-1a77a895a018.png">

https://mumbai.polygonscan.com/tx/0x45398cc6941400527f572d6791f73321a9718751ab740b8e204dc53243ac4a66

MATIC assets in the bundler
0.740209563545382995 (before)
0.740145890405986468 (after)

I'm wondering why this happened and if it's possible to prevent these bugs.

**Comment by hereokay** [comment]
Signed UserOperation: {
  "sender": "0x60bce7E35302AA2586B08f95954C73834b341014",
  "nonce": "0x6",
  "initCode": "0x",
  "callData": "0xb61d27f600000000000000000000000060bce7e35302aa2586b08f95954c73834b34101400000000000000000000000000000000000000000000000006f05b59d3b2000000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000",
  "callGasLimit": "0x909f",
  "verificationGasLimit": "0x186a0",
  "maxFeePerGas": "0x6507a5e0",
  "maxPriorityFeePerGas": "0x6507a5c0",
  "paymasterAndData": "0x",
  "preVerificationGas": "0xac0c",
  "signature": "0x945f06de63f6e20c3b69ed5582607aa4f12982af6f7bbd4c5e4b5eadddb51290735a6b354819f66963980143269b75f8e6a786d89c73fcfc7d5b4d8eb3a7d56b1b"
}
UserOpHash: 0xdfdbd1bc1e1e4960e74b62042bda41f53b41add16fa3c41e337a1c77d98d8b13

this is UserOp

**Comment by merlinana** [comment]
@hereokay Talk to Polygon  Support on the Support :[Polygon Live Support](https://matic-network.org/) so that your issue can be looked into.

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by hazim-j** [comment]
This is a known downside of running bundlers in private mode over the public mempool. There'll always a chance that the bundler will submit a bad transaction because it simulated against an outdated state or another bundler managed to submit that op first.

The short term mitigation here is to consider clients who send these ops as spam and throttle/ban them for a period of time. The best solution is integrating with [`eth_sendRawTransactionConditional`](https://notes.ethereum.org/@yoav/SkaX2lS9j). These require client teams to ship the change.

**Comment by hazim-j** [comment]
Closing for now since the solution is already planned. Feel free to re-open if you wanted to continue the discussion or had more questions.
